import { json } from "@/lib/cf";
import spec from "@/lib/api-docs/openapi.json";

// GET /api/docs/openapi.json — OpenAPI 3.0.3 spec, generated by scripts/generate-openapi.mjs
export async function GET(): Promise<Response> {
  return json(spec, 200, { "Cache-Control": "public, max-age=3600" });
}